export const POST_SHORTEN_LOADING = 'POST_SHORTEN_LOADING';
export const POST_SHORTEN_ERROR = 'POST_SHORTEN_ERROR';
export const POST_SHORTEN_SUCCESS = 'POST_SHORTEN_SUCCESS';

export const GET_ALLURLS_LOADING = 'GET_ALLURLS_LOADING';
export const GET_ALLURLS_ERROR = 'GET_ALLURLS_ERROR';
export const GET_ALLURLS_SUCCESS = 'GET_ALLURLS_SUCCESS';